language: go
go:
        - 1.6
- 1.2
- 1.3
- 1.4
- 1.5
addons:
        mariadb: '5.5'
before_install:
- echo "" > coverage.txt
- go get github.com/onsi/gomega
- go get github.com/onsi/ginkgo
- go get golang.org/x/tools/cmd/cover
install:
- ln -s $PWD $GOPATH/src/github.com/ArchieT/3manchess
- sh -c "mysql -e 'create database if not exists archiet;'; mysql archiet < $GOPATH/src/github.com/ArchieT/3manchess/server/mojsql/setup.sql"
- go get -v -t -race github.com/ArchieT/3manchess/movedet
- go get -v -t -race github.com/ArchieT/3manchess/player
- go get -v -t -race github.com/ArchieT/3manchess/interface/devengfmt
- go get -v -t -race github.com/ArchieT/3manchess/cmd/3manchess-devengfmt
- go get -v -t -race github.com/ArchieT/3manchess/cmd/3manchess-devengchan
- go get -v -t -race github.com/ArchieT/3manchess/ai/sitvalues
- go get -v -t -race github.com/ArchieT/3manchess/interface/gui
script:
- go test -v github.com/ArchieT/3manchess/game -covermode=atomic -coverprofile=tmp1.out
- cat tmp1.out >> coverage.txt
- go test -v github.com/ArchieT/3manchess/movedet -covermode=atomic -coverprofile=tmp2.out
- cat tmp2.out >> coverage.txt
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  slack:
    secure: igB8y+vprHoTX+JA9Phf3caJRJg/81wiRgcHbaC6OKUlsushz89IbzE3WAWbhJPDlAwR8pcLKbC3CKvJ0BABedZAdmssF0sMX8NeKbeWPTDPzIHCKxcSsaBAzr0lnTTyU6uajd0HsXliidUUP1wfWE8J/SvdShI3BOcd8+F6/YiIqmqwSA5mYjapD+XKKwu4SiZGhic2UHBHB+n1xHk9MSpUq1clNk+19uG2sZG+tMjFEDKmyhZCBEa1jzYBzbW7Ka5RI4et8ua70I3w8W/PKI5nrYAcEIkpBZZpzNRZNN+Koo+vPfN6FHQGbQhPHSxsqsji0/iB3hDAB2Et5KeDFDHUK+XBNBLXUNs+2ZhFndVDvMCfMI2W7YuwYlydes73Si3EZyQhewPvxwNJBWVvWRChbGAOo8iDyFYhCVaOcAIE1HcKuFp2dC3hIjbZKsaKhGFpXyC++rKDTzyHQ46EsBXvV0oi6NToiNWnTUwwW10fwXnRteU/XJ3YikS5LY2fnTuGr218jXZlIuUgpa55jFSnFf4omgFSjrAzNKoe+fNXOnU3d8DEn3zOcI87LJBN7U2yY6Y+pBQH9HIK+Bx0XxDqlkXQIZ5a/KpqAZoKtRmazTgbVBfKxdmC/UEgyfS9ZqhrbXbxnwsTbPkKJza3K/OlXyfL9A/oN6wVbxhCaPw=
